### PR TITLE
Add core Globus Compute developers as maintainers

### PR DESCRIPTION
**Pull request by rjmello**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by carterbox** [comment]
@rjmello, is this the first feedstock to which you are adding your coworkers?

If the same people will be added to all of the globus feedstocks, I believe that we can add whole conda-forge teams as maintainers for a feedstock ([example](https://github.com/conda-forge/magma-feedstock/blob/73c0e317c6e9363c2f63dadae95c54fb998ab90b/recipe/meta.yaml#L247)) which is easier to maintain because the full list of people is only maintained in one place.

My suggestion is to add the full list of people here (@conda-forge/globus-compute-endpoint) or to @conda-forge/globus-sdk. Then just use the team name for other feedstocks. Does that make sense?

**Comment by WardLT** [comment]
LGTM, to the extent of my limited understanding of the conda-forge meta.yaml

**Comment by xylar** [comment]
While I would welcome new maintainers at https://github.com/conda-forge/globus-sdk-feedstock, it doesn't look like the developers of [Globus Compute ](https://github.com/globus/globus-compute/graphs/contributors)are the same as for [Globus SDK Python](https://github.com/globus/globus-sdk-python/graphs/contributors).  @carterbox, maybe you were thinking of @conda-forge/globus-compute-sdk?

**Comment by carterbox** [comment]
@xylar, I don't know! I assume that @rjmello would know. I just suggested the globus feedstock with the shortest name. 😄

**Comment by xylar** [comment]
>  I just suggested the globus feedstock with the shortest name. 😄

Okay, sounds good.  Happy to help if `globus-sdk` ends up being the place to add everyone.

**Comment by rjmello** [comment]
Thanks for the suggestion, @carterbox and @xylar.

@xylar is correct that different Globus teams are responsible for maintaining the Globus SDK and Globus Compute SDK. I've created https://github.com/conda-forge/globus-compute-sdk-feedstock/pull/34 to add the core Globus Compute developers to @conda-forge/globus-compute-sdk, then updated this PR to reference it.

**Comment by carterbox** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
